routes/web.php
<?php

use App\Http\Controllers\KategoriController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RepliesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });



Route::get('/', function () {
    return view('index');
});
Route::get('/', [TopicController::class, 'index'])->name('topics.index');
Route::get('/topic/create', [TopicController::class, 'create'])->middleware('auth');
Route::post('/topic/kirim', [TopicController::class, 'store'])->middleware('auth')->name('topics.store');
Route::get('/topic/{id}', [TopicController::class, 'show'])->name('topics.show');
Route::get('/topic/{id}/edit', [TopicController::class, 'edit'])->middleware('auth')->name('topics.edit');
Route::put('/topic/{id}/edit', [TopicController::class, 'update'])->middleware('auth')->name('topics.update');
Route::delete('/topic/{id}/delete', [TopicController::class, 'destroy'])->middleware('auth')->name('topics.destroy');
Route::get('/search', [TopicController::class, 'search'])->name('topics.search');
// Route::get('/topic/1' , [TopicController::class, 'show']);

// CRUD Kategori 
Route::resource('/kategori',KategoriController::class)->middleware('auth');

// Authentication Laravel UI
Auth::routes();

// Testing Only
Route::get('test', function () {
    return view('test');
});

Route::resource('/profile', ProfileController::class)->middleware('auth');
Route::post('/topic/{topic}/reply', [RepliesController::class, 'store'])->middleware('auth')->name('replies.store');
Route::get('/topic/{topic}/reply/{reply}/edit', [RepliesController::class, 'edit'])->middleware('auth')->name('replies.edit');
Route::put('/topic/{topic}/reply/{reply}/edit', [RepliesController::class, 'update'])->middleware('auth')->name('replies.update');
Route::delete('/topic/{topic}/reply/{reply}/delete', [RepliesController::class, 'destroy'])->middleware('auth')->name('replies.destroy');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('title')
	Homepage -Forum
@endsection
@section('content')
	<main id="tt-pageContent" class="tt-offset-small">
    <div class="container">
        @if ($topics->isNotEmpty())
        <div class="tt-topic-list">
            <div class="tt-list-header">
                <div class="tt-col-topic">Topic</div>
                <div class="tt-col-category">Category</div>
                <div class="tt-col-category">Created</div>
            </div>
            <form action="{{route('topics.index')}}" method="GET">
                @csrf
                @foreach ($topics as $item)
            <div class="tt-item">
                <div class="tt-col-avatar">
                    <img class="tt-icon" src="{{asset('storage/avatars/' . $item->user->avatar)}}">
                </div>
                <div class="tt-col-description">
                    <h6 class="tt-title"><a href="{{route('topics.show', ['id' => $item->id] )}}">
                        {{\Illuminate\Support\Str::limit($item->judul, 50, $end='...')}}
                    </a></h6>
                    <div class="row align-items-center no-gutters">
                        <div class="col-11">
                            <ul class="tt-list-badge">
                                <li class="show-mobile"><a href="#"><span class="tt-color04 tt-badge">{{$item->kategori->nama}}</span></a></li>
                                <li><a >Created By:</a></li>
                                <li><a href="{{route('profile.show', ['profile' => $item->user_id])}}"><span class="tt-badge">{{$item->user->name}}</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tt-col-category"><span class="tt-color04 tt-badge">{{$item->kategori->nama}}</span></div>
                <div class="tt-col-category hide-mobile">{{Carbon\Carbon::parse($item->created_at)->diffForHumans()}}</div>
            </div>
            </form>
            @endforeach
            @else
            <div class="tt-wrapper-inner">
                    <h4 class="tt-title-separator"><span>No Topic Found :(</span></h4>
                </div>
            @endif
            <div class="tt-row-btn">
                <button type="button" class="btn-icon js-topiclist-showmore">
                    <svg class="tt-icon">
                      <use xlink:href="#icon-load_lore_icon"></use>
                    </svg>
                </button>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/search.blade.php
@extends('layouts.master')
@section('title')
	Search - Forum
@endsection
@section('content')
	<main id="tt-pageContent" class="tt-offset-small">
    <div class="container">
        @if ($topics->isNotEmpty())
        <div class="tt-topic-list">
            <div class="tt-list-header">
                <div class="tt-col-topic">Topic</div>
                <div class="tt-col-category">Category</div>
                <div class="tt-col-category">Created</div>
            </div>
                @foreach ($topics as $item)
            <div class="tt-item">
                <div class="tt-col-avatar">
                    <svg class="tt-icon">
                      <use xlink:href="#icon-ava-c"></use>
                    </svg>
                </div>
                <div class="tt-col-description">
                    <h6 class="tt-title"><a href="{{route('topics.show', ['id' => $item->id] )}}">
                        {{\Illuminate\Support\Str::limit($item->judul, 50, $end='...')}}
                    </a></h6>
                    <div class="row align-items-center no-gutters">
                        <div class="col-11">
                            <ul class="tt-list-badge">
                                <li class="show-mobile"><a href="#"><span class="tt-color04 tt-badge">{{$item->kategori->nama}}</span></a></li>
                                <li><a >Created By:</a></li>
                                <li><a href="{{route('profile.show', ['profile' => $item->user_id])}}"><span class="tt-badge">{{$item->user->name}}</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tt-col-category"><span class="tt-color04 tt-badge">{{$item->kategori->nama}}</span></div>
                <div class="tt-col-category hide-mobile">{{Carbon\Carbon::parse($item->created_at)->diffForHumans()}}</div>
            </div>
            @endforeach
            @else
                <div class="tt-wrapper-inner">
                    <h4 class="tt-title-separator"><span>No Topic Found :(</span></h4>
                </div>
                @endif
            <div class="tt-row-btn">
                <button type="button" class="btn-icon js-topiclist-showmore">
                    <svg class="tt-icon">
                      <use xlink:href="#icon-load_lore_icon"></use>
                    </svg>
                </button>
            </div>
        </div>
    </div>
</main>
@endsection